In [1]:
#1 Write a program to distinguish between Array Indexing and Fancy Indexing.
import numpy as np

# Create a NumPy array
arr = np.array([0, 1, 2, 3, 4, 5])

# Array Indexing
print("Array Indexing:")
index = 2
print(f"Element at index {index}: {arr[index]}")

slice_start = 1
slice_end = 4
print(f"Elements from index {slice_start} to {slice_end}: {arr[slice_start:slice_end]}")

# Fancy Indexing
print("\nFancy Indexing:")
index_array = np.array([1, 3, 5])
print(f"Elements at fancy indices {index_array}: {arr[index_array]}")



Array Indexing:
Element at index 2: 2
Elements from index 1 to 4: [1 2 3]

Fancy Indexing:
Elements at fancy indices [1 3 5]: [1 3 5]
Elements where bool_array is True: [0 2 4]


In [2]:
#2Execute the 2D array Slicing.
import numpy as np

# Create a 2D NumPy array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Basic 2D Slicing
print("Original Matrix:")
print(matrix)

# Slicing rows and columns
row_slice = matrix[0:2, :]  # Rows 0 and 1, all columns
col_slice = matrix[:, 1:3]  # All rows, columns 1 and 2

print("\nSliced Rows:")
print(row_slice)

print("\nSliced Columns:")
print(col_slice)

# Accessing specific elements
element = matrix[1, 2]  # Row 1, Column 2
print("\nElement at row 1, column 2:", element)




Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced Rows:
[[1 2 3]
 [4 5 6]]

Sliced Columns:
[[2 3]
 [5 6]
 [8 9]]

Element at row 1, column 2: 6


In [19]:
#3Create the 5-Dimensional arrays using ‘ndmin’.
import numpy as np

arr=np.array([1,2,3,4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [21]:
#4 Reshape the array from 1-D to 2-D array..
import numpy as np

# Create a 1-D array
one_dimensional_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1-D array to a 2-D array with 3 rows and 2 columns
two_dimensional_array = one_dimensional_array.reshape(3, 2)

# Alternatively, you can use np.reshape()
# two_dimensional_array = np.reshape(one_dimensional_array, (3, 2))

# Print the original and reshaped arrays
print("Original 1-D Array:")
print(one_dimensional_array)

print("\nReshaped 2-D Array:")
print(two_dimensional_array)


Original 1-D Array:
[1 2 3 4 5 6]

Reshaped 2-D Array:
[[1 2]
 [3 4]
 [5 6]]


In [5]:
#5 Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().
import numpy as np

# Create two 1-D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them along a new axis (axis=0 by default)
stacked_array = np.stack((array1, array2))

print("np.stack() result:")
print(stacked_array)


np.stack() result:
[[1 2 3]
 [4 5 6]]


In [6]:
#hstack
import numpy as np

# Create two 1-D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them horizontally
horizontal_stack = np.hstack((array1, array2))

print("np.hstack() result:")
print(horizontal_stack)


np.hstack() result:
[1 2 3 4 5 6]


In [7]:
#vstack
import numpy as np

# Create two 1-D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them vertically
vertical_stack = np.vstack((array1, array2))

print("np.vstack() result:")
print(vertical_stack)


np.vstack() result:
[[1 2 3]
 [4 5 6]]


In [8]:
#dstack
import numpy as np

# Create two 2-D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack them along the third axis
depth_stack = np.dstack((array1, array2))

print("np.dstack() result:")
print(depth_stack)


np.dstack() result:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [9]:
#6 Q6. Perform the searchsort method in Numpy array.
import numpy as np

# Create a sorted 1-D array
sorted_array = np.array([1, 3, 5, 7, 9, 11, 13])

# Values to search for
values_to_search = [4, 8, 13]

# Perform searchsorted
indices = np.searchsorted(sorted_array, values_to_search)

# Print the results
for value, index in zip(values_to_search, indices):
    print(f"Value {value} should be inserted at index {index} to maintain sorted order.")


Value 4 should be inserted at index 2 to maintain sorted order.
Value 8 should be inserted at index 4 to maintain sorted order.
Value 13 should be inserted at index 6 to maintain sorted order.


In [10]:
#7. Create Numpy Structured array using your domain features.
import numpy as np

# Define the data types for the structured array
book_dtype = np.dtype([
    ('title', 'U50'),        # Unicode string with max length 50 characters
    ('author', 'U50'),
    ('publication_year', int),  # Integer for publication year
    ('isbn', 'U13')           # Unicode string with max length 13 characters (ISBN-13)
])

# Create a structured array with book information
books = np.array([
    ('Book 1', 'Author 1', 2020, '978-1234567890'),
    ('Book 2', 'Author 2', 2015, '978-9876543210'),
    ('Book 3', 'Author 3', 2012, '978-0123456789'),
], dtype=book_dtype)

# Print the structured array
print(books)


[('Book 1', 'Author 1', 2020, '978-123456789')
 ('Book 2', 'Author 2', 2015, '978-987654321')
 ('Book 3', 'Author 3', 2012, '978-012345678')]


In [11]:
#8. Create Data frame using List and Dictionary.
import pandas as pd

# Create a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [28, 24, 22],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      Name  Age         City
0    Alice   28     New York
1      Bob   24  Los Angeles
2  Charlie   22      Chicago


In [12]:
#9 Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
#missing data from the dataset.
#• isnull()
#• notnull()
#• dropna()
#• fillna()
#• replace()
#• interpolate()

import pandas as pd
import numpy as np

# Create a DataFrame with synthetic student data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20, 21, np.nan, 22, 23],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'Score': [90, np.nan, 75, np.nan, 88]
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Find missing data with isnull()
missing_data = df.isnull()
print("\nMissing Data (True where data is missing):\n", missing_data)

# Find non-missing data with notnull()
non_missing_data = df.notnull()
print("\nNon-Missing Data (True where data is not missing):\n", non_missing_data)

# Drop rows with missing data using dropna()
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing data:")
print(df_dropped)

# Fill missing data with fillna()
df_filled = df.fillna({'Age': df['Age'].mean(), 'Score': df['Score'].median()})
print("\nDataFrame after filling missing data:")
print(df_filled)

# Replace missing data with interpolate()
df_interpolated = df.interpolate()
print("\nDataFrame after interpolating missing data:")
print(df_interpolated)


Original DataFrame:
      Name   Age  Gender  Score
0    Alice  20.0  Female   90.0
1      Bob  21.0    Male    NaN
2  Charlie   NaN    Male   75.0
3    David  22.0    Male    NaN
4      Eva  23.0  Female   88.0

Missing Data (True where data is missing):
     Name    Age  Gender  Score
0  False  False   False  False
1  False  False   False   True
2  False   True   False  False
3  False  False   False   True
4  False  False   False  False

Non-Missing Data (True where data is not missing):
    Name    Age  Gender  Score
0  True   True    True   True
1  True   True    True  False
2  True  False    True   True
3  True   True    True  False
4  True   True    True   True

DataFrame after dropping rows with missing data:
    Name   Age  Gender  Score
0  Alice  20.0  Female   90.0
4    Eva  23.0  Female   88.0

DataFrame after filling missing data:
      Name   Age  Gender  Score
0    Alice  20.0  Female   90.0
1      Bob  21.0    Male   88.0
2  Charlie  21.5    Male   75.0
3    David  22.0 

C:\Users\jagrati jain\AppData\Local\Temp\ipykernel_7756\182688374.py:38: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


In [13]:
#10. Perform the Hierarchical Indexing in the above created dataset.
import pandas as pd
import numpy as np

# Create a DataFrame with synthetic student data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20, 21, np.nan, 22, 23],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'Score': [90, np.nan, 75, np.nan, 88]
}

# Create a MultiIndex DataFrame with two levels of indexing
arrays = [
    ['Class A', 'Class A', 'Class B', 'Class B', 'Class C'],
    ['Student 1', 'Student 2', 'Student 1', 'Student 2', 'Student 1']
]

index = pd.MultiIndex.from_arrays(arrays, names=('Class', 'Student'))

df = pd.DataFrame(data, index=index)

# Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)


DataFrame with Hierarchical Indexing:
                      Name   Age  Gender  Score
Class   Student                                
Class A Student 1    Alice  20.0  Female   90.0
        Student 2      Bob  21.0    Male    NaN
Class B Student 1  Charlie   NaN    Male   75.0
        Student 2    David  22.0    Male    NaN
Class C Student 1      Eva  23.0  Female   88.0
